# Generated by Django 3.0.7 on 2021-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Designates whether the user validate into email.', verbose_name='valid status'),
        ),
    ]
