# Generated by Django 3.0.7 on 2021-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.CharField(max_length=30)),
                ('is_private', models.BooleanField(default=False)),
                ('industries', models.ManyToManyField(blank=True, related_name='industries', to='industry.Industry')),
                ('technologies', models.ManyToManyField(blank=True, related_name='technologies', to='technology.Technology')),
            ],
        ),
    ]
